#!/usr/bin/env python3
"""Appendix table: the 30-venture reference set on one portrait page.

One numbered, two-line block per venture: a hand-written one-line summary with
the pseudonymized URL beneath it, a stacked Goal/Raised money cell, and a
stacked Start/End dates cell.  Rows follow the evaluator ranking
(analysis/evalrank-30.csv); the bottom half is the seed set.  Writes
figs/reference-set.tex (the tabular body; the manuscript wraps it in a float).

Usage: python3 analysis/build_universe_table.py
"""
import csv
from pathlib import Path
from datetime import date

BASE = Path(__file__).resolve().parent.parent

# One-line summaries (<= ~76 chars, one line at the summary-column width), condensed from the campaign summaries'
# own one-sentence summaries; no invented facts.
GIST = {
    "dreamie": "Bedside sleep device with audio, sunrise alarms, and private listening",
    "fraction": "Modular, repairable vacuum with self-diagnostics and UVC disinfection",
    "prolo-ring": "Wearable ring giving cursor control, shortcuts, and air gestures",
    "ubo-pod": "Open-source Raspberry-Pi device for voice-and-vision assistants",
    "pictomic": "Computer-controlled macro rail that automates precise focus stacking",
    "humanecheck": "App that scans barcodes to grade animal welfare and suggest alternatives",
    "lifesummary": "AI service answering questions about insurance and estate documents",
    "kujietool": "Compact desktop milling machine with professional-grade accuracy",
    "toolkaiser": "Software that scans hand tools and exports precisely scaled outline files",
    "robotin-r2": "Autonomous appliance that deep-vacuums, machine-washes, and dries carpets",
    "cyberdesk": "Case-management platform for cybersecurity investigations and reporting",
    "cop-rights": "Free app with state-specific guidance on drivers' rights at traffic stops",
    "pickup": "App for finding quality pickup basketball games and tracking performance",
    "zulni": "Journaling companion with stress-aware prompts and optional biofeedback",
    "soloist": "Loop-pedal-style app where musicians record ideas others grow into tracks",
    "clockchain": "Tool anchoring a file's fingerprint to a public time-stamped ledger",
    "hply": "Donation app connecting givers with vetted nonprofits and impact updates",
    "angelry": "Heirloom jewelry of leather cultivated in bioreactors from cow skin cells",
    "lockguard": "Portable home-security device installing without tools or Wi-Fi",
    "sale-finder": "App mapping local yard and estate sales live, with routes and rewards",
    "genaix": "Learning platform for human-centered AI education with an AI mentor",
    "bugout-battery": "Rugged off-grid battery-and-solar system for emergencies and RVs",
    "rent-a-bee": "Hive-sponsorship subscription linking supporters with local beekeepers",
    "hooper": "App where basketball players find games, check in, and build rankings",
    "remotion-ai": "AI video analysis delivering sprint-coaching feedback on athletes' form",
    "viaia": "AI travel assistant for trustworthy local services in Venezuela",
    "lumivisor": "Transparent LED film for helmet visors that displays expressions",
    "voyagx": "Social travel app for planning trips, splitting costs, meeting companions",
    "kebo": "Spring-loaded bottle opener using kinetic energy to eject caps cleanly",
    "my-story": "Children's storytelling system pairing a print book with an AR app",
}


def tex_escape(s):
    s = (s.replace("\\", "").replace("&", "\\&").replace("%", "\\%")
          .replace("#", "\\#").replace("_", "\\_").replace("$", "\\$"))
    # typographic quotes: "..." -> ``...'' (single quotes in the gists are
    # apostrophes, which LaTeX already sets correctly)
    while '"' in s:
        s = s.replace('"', "``", 1).replace('"', "''", 1)
    return s


def fmt_money(x):
    return f"\\${int(round(float(x))):,}"


def fmt_date(s):
    return date.fromisoformat(s).strftime("%b~%-d")


def main():
    csv.field_size_limit(10**9)
    rows = {r["id"]: r for r in csv.DictReader(open(BASE / "in" / "projects.csv",
                                                    encoding="utf-8-sig"))}
    rank = list(csv.DictReader(open(BASE / "analysis" / "evalrank-30.csv")))
    order = [r["id"] for r in rank]
    perf = {r["id"]: float(r["universe_win_rate"]) for r in rank}
    missing = set(rows) - set(GIST)
    assert not missing, f"gists missing for: {missing}"

    # Column widths fill \textwidth exactly.  The unlabeled rank column uses a
    # fixed narrow width, and the summary column absorbs the remainder.
    summary_w = ("\\dimexpr\\textwidth-0.4cm-0.35em-2.2cm-1.5cm-1.2cm"
                 "-6\\tabcolsep\\relax")
    lines = [
        "% Auto-generated by analysis/build_universe_table.py; do not edit.",
        f"\\begin{{tabular}}{{@{{}}>{{\\raggedleft\\arraybackslash}}p{{0.4cm}}"
        f"@{{\\hspace{{0.35em}}}}p{{2.2cm}}L{{{summary_w}}}"
        ">{\\raggedleft\\arraybackslash}p{1.5cm}p{1.2cm}@{}}",
        "\\toprule",
        " & \\textbf{Venture}\\newline\\textbf{(Performance)} & "
        "\\textbf{Brief summary}\\newline \\textbf{URL} & "
        "\\textbf{Goal}\\par \\textbf{Raised} & "
        "\\textbf{Start}\\newline \\textbf{End} \\\\",
        "\\midrule",
    ]
    for i, vid in enumerate(order):
        if i == 15:
            lines.append("\\addlinespace[1pt]\\midrule\\addlinespace[1pt]")
        r = rows[vid]
        venture = f"\\texttt{{{tex_escape(vid)}}}\\newline ({100*perf[vid]:.1f}\\%)"
        display_url = r["url"].replace("https://", "").replace("http://", "")
        summary = (f"{tex_escape(GIST[vid])}\\newline"
                   f"\\adjustbox{{max width=\\linewidth}}{{\\href{{{r['url']}}}"
                   f"{{\\fontsize{{5}}{{5.8}}\\selectfont {display_url}}}}}")
        money = f"{fmt_money(r['goal'])}\\par {fmt_money(r['raised'])}"
        dates = f"{fmt_date(r['launch'])}\\newline{{}}{fmt_date(r['deadline'])}"
        lines.append(f"{i + 1} & {venture} & {summary} & {money} & {dates} \\\\"
                     "\\addlinespace[0.25pt]")
    lines += ["\\bottomrule", "\\end{tabular}"]
    (BASE / "figs" / "reference-set.tex").write_text("\n".join(lines) + "\n")
    print(f"wrote figs/reference-set.tex ({len(order)} two-line blocks, "
          "evaluator-rank order, seeds below the rule)")


if __name__ == "__main__":
    main()
